apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game-ops
resources:
  - base/namespace.yaml
  - base/configmap.yaml
  - base/secret.yaml
  - infra/infra.yaml
  - apps/applications.yaml
  - networking/ingress.yaml
  - monitoring/monitoring.yaml
configMapGenerator:
  - name: mysql-init
    files:
      - init.sql=configs/init.sql
  - name: prometheus-config
    files:
      - prometheus.yml=configs/prometheus.yml
      - alerts.yml=configs/alerts.yml
  - name: alertmanager-config
    files:
      - alertmanager.yml=configs/alertmanager.yml
  - name: grafana-provisioning
    files:
      - datasource.yml=configs/grafana-datasource.yml
      - dashboard.yml=configs/grafana-dashboard-provider.yml
  - name: grafana-dashboard
    files:
      - game-services-overview.json=configs/game-services-overview.json
generatorOptions:
  disableNameSuffixHash: true

