apiVersion: v1
kind: Secret
metadata:
  name: game-app-secret
  namespace: game-ops
type: Opaque
stringData:
  MYSQL_PASSWORD: game_password
  MYSQL_ROOT_PASSWORD: root_password
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin

