apiVersion: v1
kind: Namespace
metadata:
  name: game-ops-system
  labels:
    app.kubernetes.io/name: game-platform-operator
    app.kubernetes.io/part-of: game-k8s-ops-practice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-platform-operator
  namespace: game-ops-system
  labels:
    app.kubernetes.io/name: game-platform-operator
    app.kubernetes.io/part-of: game-k8s-ops-practice